syntax = "proto3";

package proxy.v1;

import "google/protobuf/struct.proto";

option go_package = "github.com/ihgazi/VectorProxy/proto/proxy/v1;proxyv1";

message SearchRequest {
  repeated float vector = 1;
  int32 top_k = 2;
  string collection = 3;
  google.protobuf.Struct filter = 4;
}

message SearchResult {
  string id = 1;
  float score = 2;
  google.protobuf.Struct payload = 3;
}

message SearchResponse {
  repeated SearchResult results = 1;
}

service ProxyService {
  rpc Search(SearchRequest) returns (SearchResponse);
}
